"""
==============================================================================
EduAssess AI
------------------------------------------------------------------------------
Version : 1.0.0
Module  : Review Assessment
==============================================================================
"""

import re
import streamlit as st

# =============================================================================
# Page Configuration
# =============================================================================

st.set_page_config(
    page_title="Review Assessment",
    layout="wide",
)

st.title("📖 Review Assessment")

# =============================================================================
# Explanation Renderer
# =============================================================================


def render_explanation(explanation: str):
    """
    Render structured explanation generated by Gemini.
    """

    if not explanation:
        st.info("No explanation available.")
        return

    sections = {}

    current_heading = "GENERAL"
    sections[current_heading] = []

    heading_pattern = re.compile(
        r"^(CONCEPT|FORMULA|SOLUTION|WHY CORRECT|WHY OTHER OPTIONS|CORRECT ANSWER|EXAM TIP|REMEMBER|MEMORY TRICK|QUICK REVISION|COMMON MISTAKE|COMMON MISTAKES):?$",
        re.IGNORECASE,
    )

    for line in explanation.splitlines():

        line = line.strip()

        if not line:
            continue

        match = heading_pattern.match(line)

        if match:

            current_heading = match.group(1).upper()

            sections[current_heading] = []

        else:

            sections[current_heading].append(line)

    heading_icons = {
        "CONCEPT": "📘",
        "FORMULA": "🧮",
        "SOLUTION": "📝",
        "WHY CORRECT": "✅",
        "WHY OTHER OPTIONS": "❌",
        "CORRECT ANSWER": "🎯",
        "EXAM TIP": "💡",
        "REMEMBER": "🧠",
        "MEMORY TRICK": "🧩",
        "QUICK REVISION": "📚",
        "COMMON MISTAKE": "⚠️",
        "COMMON MISTAKES": "⚠️",
        "GENERAL": "📖",
    }

    display_order = [
        "CONCEPT",
        "FORMULA",
        "SOLUTION",
        "WHY CORRECT",
        "WHY OTHER OPTIONS",
        "CORRECT ANSWER",
        "EXAM TIP",
        "REMEMBER",
        "MEMORY TRICK",
        "QUICK REVISION",
        "COMMON MISTAKE",
        "COMMON MISTAKES",
        "GENERAL",
    ]

    for heading in display_order:

        if heading not in sections:
            continue

        content = "\n".join(sections[heading]).strip()

        if not content:
            continue

        # ---------------------------------------------------------
        # CONCEPT
        # ---------------------------------------------------------

        if heading == "CONCEPT":

            st.markdown("---")
            st.markdown("## 📘 **CONCEPT**")
            st.info(content)

        # ---------------------------------------------------------
        # FORMULA
        # ---------------------------------------------------------

        elif heading == "FORMULA":

            st.markdown("---")
            st.markdown("## 🧮 **FORMULA**")

            st.code(
                content,
                language="text",
            )

        # ---------------------------------------------------------
        # SOLUTION
        # ---------------------------------------------------------

        elif heading == "SOLUTION":

            st.markdown("## 📝 **STEP-BY-STEP SOLUTION**")

            lines = content.splitlines()

            for line in lines:

                line = line.strip()

                if not line:
                    continue

                # -------------------------------------------------
                # Step Heading
                # -------------------------------------------------

                if line.startswith("Step"):

                    st.markdown(f"### 🔹 {line}")

                # -------------------------------------------------
                # Calculation Heading
                # -------------------------------------------------

                elif line.startswith("Calculation"):

                    st.markdown("**Calculation**")

                # -------------------------------------------------
                # Final Answer Heading
                # -------------------------------------------------

                elif line.startswith("Final Answer"):

                    st.success(line)

                # -------------------------------------------------
                # Normal Line
                # -------------------------------------------------

                else:

                    st.write(line)

        # ---------------------------------------------------------
        # WHY CORRECT
        # ---------------------------------------------------------

        elif heading == "WHY CORRECT":

            st.markdown("## ✅ **WHY THIS ANSWER IS CORRECT**")
            st.success(f"✅ {content}")

        # ---------------------------------------------------------
        # WHY OTHER OPTIONS
        # ---------------------------------------------------------

        elif heading == "WHY OTHER OPTIONS":

            st.markdown("## ❌ **WHY OTHER OPTIONS ARE INCORRECT**")

            for line in content.splitlines():

                line = line.strip()

                if not line:
                    continue

                if (
                    line.startswith("A:")
                    or line.startswith("B:")
                    or line.startswith("C:")
                    or line.startswith("D:")
                ):

                    st.markdown(f"**{line}**")

                elif line == "Correct Option":

                    st.success("✔ Correct Option")

                else:

                    st.write(line)

        # ---------------------------------------------------------
        # CORRECT ANSWER
        # ---------------------------------------------------------

        elif heading == "CORRECT ANSWER":

            st.markdown("## 🎯 **FINAL ANSWER**")
            st.success(f"🎯 {content}")

        # ---------------------------------------------------------
        # EXAM TIP
        # ---------------------------------------------------------

        elif heading == "EXAM TIP":

            st.markdown("## 💡 **EXAM TIP**")
            st.info(f"💡 {content}")

        # ---------------------------------------------------------
        # REMEMBER
        # ---------------------------------------------------------

        elif heading == "REMEMBER":

            st.markdown("## 🧠 **REMEMBER THIS**")
            st.info(f"🧠 {content}")
        # ---------------------------------------------------------
        # MEMORY TRICK
        # ---------------------------------------------------------

        elif heading == "MEMORY TRICK":

            st.markdown("---")
            st.markdown("## 🧩 **MEMORY TRICK**")

            st.success(f"🧩 {content}")

        # ---------------------------------------------------------
        # QUICK REVISION
        # ---------------------------------------------------------
        elif heading == "QUICK REVISION":

            st.markdown("---")
            st.markdown("## 📝 **QUICK REVISION**")
            st.success("📚 One-minute Revision")
            for line in content.splitlines():

                if line.strip():

                    st.markdown(f"• {line}")

        # ---------------------------------------------------------
        # COMMON MISTAKE(S)
        # ---------------------------------------------------------

        elif heading in ["COMMON MISTAKE", "COMMON MISTAKES"]:

            st.markdown("## ⚠️ **COMMON MISTAKE**")
            st.error(f"⚠️ {content}")

        # ---------------------------------------------------------
        # DEFAULT
        # ---------------------------------------------------------

        else:

            st.markdown(f"## {heading_icons.get(heading,'📄')} **{heading}**")

            st.write(content)

        st.divider()


# =============================================================================
# Validate Session
# =============================================================================

results = st.session_state.get("results")

if results is None:

    st.warning("No completed assessment found.")

    if st.button(
        "📝 Create Assessment",
        use_container_width=True,
    ):

        st.switch_page("pages/02_Create_Assessment.py")

    st.stop()

# =============================================================================
# Filters
# =============================================================================

st.sidebar.header("Review Filters")

review_mode = st.sidebar.radio(
    "Show",
    [
        "All Questions",
        "Incorrect Only",
        "Correct Only",
    ],
)

option_labels = ["A", "B", "C", "D"]

# =============================================================================
# Display Questions
# =============================================================================

displayed = 0
for item in results:

    # ---------------------------------------------------------
    # Apply Filter
    # ---------------------------------------------------------

    if review_mode == "Incorrect Only" and item["is_correct"]:
        continue

    if review_mode == "Correct Only" and not item["is_correct"]:
        continue

    displayed += 1

    # ---------------------------------------------------------
    # Question Header
    # ---------------------------------------------------------

    col1, col2 = st.columns([5, 2])

    with col1:

        st.subheader(f"Question {item['question_number']}")

    with col2:

        if item["is_correct"]:
            st.success("✅ Correct")
        else:
            st.error("❌ Incorrect")

    # ---------------------------------------------------------
    # Context
    # ---------------------------------------------------------

    if item["context"]:

        if str(item["context"]).strip():

            st.info(item["context"])

    # ---------------------------------------------------------
    # Question
    # ---------------------------------------------------------

    st.markdown(f"### {item['question']}")

    # ---------------------------------------------------------
    # Options
    # ---------------------------------------------------------

    st.markdown("### Options")

    for index, option in enumerate(item["options"]):

        if index < len(option_labels):
            label = option_labels[index]
        else:
            label = chr(65 + index)

        if label == item["correct_answer"]:

            st.write(f"**{label}. {option}** ✅")

        elif label == item["user_answer"]:

            st.write(f"**{label}. {option}** ❌")

        else:

            st.write(f"{label}. {option}")

    # ---------------------------------------------------------
    # Your Answer / Correct Answer
    # ---------------------------------------------------------

    col1, col2 = st.columns(2)

    with col1:

        if item["user_answer"]:

            user_index = ord(item["user_answer"]) - 65

            if 0 <= user_index < len(item["options"]):

                st.info(
                    f"**Your Answer**\n\n"
                    f"{item['user_answer']}. "
                    f"{item['options'][user_index]}"
                )

            else:

                st.info(item["user_answer"])

        else:

            st.warning("Not Attempted")

    with col2:

        correct_index = ord(item["correct_answer"]) - 65

        st.success(
            f"**Correct Answer**\n\n"
            f"{item['correct_answer']}. "
            f"{item['options'][correct_index]}"
        )

    # ---------------------------------------------------------
    # Explanation
    # ---------------------------------------------------------

    with st.expander(
        "📘 Learn the Concept",
        expanded=False,
    ):
        render_explanation(item["explanation"])

    col1, col2 = st.columns(2)

    with col1:

        st.caption(f"Difficulty : {item['difficulty']}")

    with col2:

        st.caption(f"Bloom Level : {item['bloom_level']}")

    # ---------------------------------------------------------
    # Active Recall
    # ---------------------------------------------------------

    st.markdown("---")

    st.success(
        "🔁 **Active Recall Challenge**\n\n"
        "Close this explanation and try solving the question again "
        "without looking at the answer."
    )


# =============================================================================
# Empty State
# =============================================================================

if displayed == 0:

    st.info("No questions match the selected filter.")

# =============================================================================
# Navigation
# =============================================================================

st.divider()

col1, col2 = st.columns(2)

with col1:

    if st.button(
        "📊 Back to Results",
        use_container_width=True,
    ):

        st.switch_page("pages/04_Results.py")

with col2:

    if st.button(
        "📝 Create New Assessment",
        use_container_width=True,
        type="primary",
    ):

        for key in [
            "assessment",
            "answers",
            "results",
            "score",
            "total_questions",
        ]:

            st.session_state.pop(key, None)

        st.switch_page("pages/02_Create_Assessment.py")
